### ISSUE TITLE
Can not train the model

### ISSUE THREAD

**Issue by Masahiro1002** [MasazI/cnn_depth_tensorflow#5]
Hi, 

I can not train the model in this code. I checked issue #[1] and #[3] and fixed them in the code.
However, the code can not be trained the model and I don't know why.

Does anyone train the model in this code?

Finally, thank you for providing a readable code.

**Comment by pippy360** [comment]
Hi Masahiro, 

I managed to get it working, if you clone this repo at this changelist it should work (just run "python task.py" after installing all the needed pip stuff):
https://github.com/pippy360/workingFromDepthRepo/commit/5ab2a2282b47f3d6e69d8ab5ddf468bf38ca193e

Get back to me if it doesn't work and I can help you through it

**Comment by Masahiro1002** [comment]
HI, pippy,

Thank you for your reply.
I tried to do what you said, however, I got a error like below,

I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "task.py", line 127, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "task.py", line 123, in main
    train()
  File "task.py", line 32, in train
    logits = model.inference_refine(images, coarse, keep_conv, keep_hidden)
  File "/home/yamaguchi/workspace/workingFromDepthRepo/model.py", line 78, in inference_refine
    fine2 = tf.concat([fine1_dropout, coarse7_output], 3)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))

And I am not sure where is the wrong point in the original code...

Best regards,

**Comment by Masahiro1002** [comment]
My python's version is caused this error. 
I fixed the code and solve the error.

However, I  cannot get a good result. I think we have to train the coarse model and after that we should train the fine model using the coarse train model. 
In this code, we can get the coarse train model, however, we can not train the fine model using the coarse train model. 

I thought something is wrong in the save function or concatenate function.

thanks,
